require("default.plugins.packer")
require("default.plugins.telescope")
require("default.plugins.colors")
require("default.plugins.treesitter")
require("default.plugins.lualine")
require("default.plugins.harpoon")
require("default.plugins.lsp")
